name: Server CI

on:
  push:
    branches: [feat/*]
    paths:
      - 'packages/backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Tests with Coverage
        run: npm run test:cov -w packages/backend

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint -w packages/backend
